# Generated by Django 4.2.3 on 2023-10-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('worked_hours', models.IntegerField()),
                ('supplier_name', models.CharField(max_length=500)),
                ('po', models.CharField(max_length=100)),
            ],
        ),
    ]
