# Generated by Django 4.2.3 on 2023-10-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docket',
            name='rate_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
